Technology: XLK
Semiconductors: SMH
Financials: XLF
Healthcare: XLV
Energy: XLE
Utilities: XLU
Industrials: XLI
Consumer_Discretionary: XLY
Consumer_Staples: XLP
Real_Estate: XLRE
Materials: XLB
Communication_Services: XLC
Clean_Energy: ICLN
Uranium: URA
Aerospace_Defense: ITA
Software: IGV
Cloud: SKYY
Cybersecurity: CIBR
Quantum: QTUM
Space: UFO
